export const oldMenuTypes = {
    MENU_TYPE_SUBMENU: 0,
    MENU_TYPE_SUBMENU_GRAPHC: 1,
    MENU_TYPE_SETTING: 2,
    MENU_TYPE_SETTING_ON_PARAMETER: 3,
    MENU_TYPE_SETTING_ON_SELECT: 4,
    MENU_TYPE_SETTING_MULTY_SELECT_ONE_STAGE: 5,
    MENU_TYPE_MONITOR: 6,
    MENU_TYPE_HOME: 7,
    MENU_TYPE_SETTING_MULTY_GROUP: 8,
    MENU_TYPE_CHART: 9,

    ITEM_TYPE_SUBMENU_GRAPHC: 10,
    ITEM_TYPE_SETTING_ON_PARAMETER: 11,
    ITEM_TYPE_SETTING_ON_SELECT: 12,
    ITEM_TYPE_SETTING_MULTY_SELECT_ONE_STAGE: 13,
    ITEM_TYPE_SETTING_SHOW_OPTIONS: 14,

    ITEM_TYPE_MULTY_GROUP_PROPERTY: 15,

    ITEM_TYPE_MONITOR_SINGLE_INT: 16,
    ITEM_TYPE_MONITOR_SINGLE_INT16: 17,
    ITEM_TYPE_MONITOR_SINGLE_INT32: 18,
    ITEM_TYPE_MONITOR_SINGLE_FLOAT: 19,
    ITEM_TYPE_MONITOR_ON_SELECT: 20,
    ITEM_TYPE_MONITOR_LABEL: 21,

    ITEM_TYPE_COSTOM_FUNCTION: 22,
    ITEM_TYPE_COSTOM_FUNCTION_OK: 23,

    ITEM_TYPE_CHART: 24,
};
